[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"